INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('s.stazzone@unisa.it', 'password', 'susetta', 'stazzone', '395056603668379');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('e.Lorusso@unisa.it', 'password', 'ado', 'vaccaro', '296194954297969');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('a.vaccaro@unisa.it', 'password', 'fidaldo', 'accadia', '292829102553710');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('a.ahamed@unisa.it', 'password', 'santoro', 'lecca', '222019119392721');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('f.accadia@unisa.it', 'password', 'nara', 'gnani', '497592400418078');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('g.valvano@unisa.it', 'password', 'gelmina', 'bevilacqua', '548437127530803');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('s.lecca@unisa.it', 'password', 'oronzino', 'avendato', '715238475458099');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('n.borgat-wohlbang@unisa.it', 'password', 'neda', 'vella', '594107129803818');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('n.gnani@unisa.it', 'password', 'efro', 'rucci', '610962423075570');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('u.cecchetti@unisa.it', 'password', 'finaldo', 'di tuoro ', '975119020173813');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('g.bevilacqua@unisa.it', 'password', 'massimiliana', 'Ferretti', '339225199326008');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('o.mezzogori@unisa.it', 'password', 'turrido', 'lucchesini', '309047619826183');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('o.avendato@unisa.it', 'password', 'altea', 'comini', '312308445326185');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('r.oliva@unisa.it', 'password', 'rondino', 'Marra', '663712687977276');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('n.vella@unisa.it', 'password', 'illuminata', 'palatano', '183461841485653');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('m.gnani@unisa.it', 'password', 'cadornino', 'Martini', '955610673002514');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('b.rainesi@unisa.it', 'password', 'beltrando', 'rainesi', '340372286470549');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('d.dotti@unisa.it', 'password', 'deni', 'dotti', '324574981359040');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('g.Piazza@unisa.it', 'password', 'glenda', 'Piazza', '286609782757251');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('e.ceccaroni@unisa.it', 'password', 'ermilda', 'ceccaroni', '425477672591019');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('o.romani bergonzo@unisa.it', 'password', 'orlindo', 'romani bergonzo', '868744858658246');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('o.callegarini@unisa.it', 'password', 'orina', 'callegarini', '680347618078736');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('e.Bellini@unisa.it', 'password', 'emio', 'Bellini', '667867667001817');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('f.laurenti@unisa.it', 'password', 'fido', 'laurenti', '258982611266776');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('f.usami@unisa.it', 'password', 'filocia', 'usami', '813489409456352');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('n.zandoli@unisa.it', 'password', 'nilo', 'zandoli', '883634561298625');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('r.zak@unisa.it', 'password', 'rosso', 'zak', '965746975215717');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('a.bellettini@unisa.it', 'password', 'almiro', 'bellettini', '297599235412904');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('g.meucci@unisa.it', 'password', 'giacobbe', 'meucci', '417458044785605');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('e.patruno@unisa.it', 'password', 'everardo', 'patruno', '851084842850817');
INSERT INTO `eTraining`.`FunzionarioSegreteria` (`Email`, `Password`, `Nome`, `Cognome`, `CodiceFiscale`)VALUES ('r.pierucci @unisa.it', 'password', 'romildo', 'pierucci ', '944897864308136');
